version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./etc/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_DATABASE: ambulancecalls
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

  flask-app-prd2:
    build: .
    ports:
      - "5000:5000"
    environment:
      MATRIX_HOMESERVER_URL: "https://maps.googleapis.com"
      ACCESS_KEY: "your_access_key"
      MONGO_URI: "mongodb://root:root@mongodb:27017/ambulancecalls?authSource=admin&authMechanism=SCRAM-SHA-1"  # Use the MongoDB container name
      MONGO_DB: "mydatabase"
      MONGO_COLLECTION: "mycollection"
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  